development:
  sessions:
    default:
      database: mongo_rugl_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: mongo_rugl_test
      hosts:
        - localhost:27017
